"""Guide text for admin Edit/Remove (v2.2.1): rewrites svsAdmin.table3 and tyrantAdmin.deleteBody in all 9 languages."""
import json, os

BASE = os.path.expanduser('~/ai/fun/wos/wos-events/frontend/src/i18n/locales')
SVS = {
 'en': 'Edit and Remove: each row has a pencil and a bin. The pencil opens the sign-up with the player ID locked: battle hours, Discord voice chat, camp level and tier per troop. Name, alliance and troops are shared with the other events, and a blank troop level keeps what is stored. The bin asks first; if the player is in the battle plan it says where, and removing them takes them out of the plan too (a leader\'s rally card stays, without a leader). Their profile is kept. In a closed round both buttons are greyed out.',
 'es': 'Editar y Quitar: cada fila tiene un lápiz y una papelera. El lápiz abre la inscripción con el ID de jugador bloqueado: horas de batalla, chat de voz de Discord, nivel de campamento y rango por tropa. Nombre, alianza y tropas se comparten con los demás eventos, y un nivel de tropa vacío mantiene lo guardado. La papelera pregunta antes; si el jugador está en el plan de batalla, dice dónde, y al quitarlo también sale del plan (la tarjeta de rally de un líder se queda, sin líder). Su perfil se conserva. En una ronda cerrada ambos botones están en gris.',
 'fr': 'Modifier et Retirer : chaque ligne a un crayon et une corbeille. Le crayon ouvre l’inscription avec l’ID joueur verrouillé : heures de bataille, chat vocal Discord, niveau de camp et palier par troupe. Le nom, l’alliance et les troupes sont partagés avec les autres événements, et un niveau de troupe vide garde la valeur enregistrée. La corbeille demande confirmation ; si le joueur est dans le plan de bataille, elle indique où, et le retirer le sort aussi du plan (la carte de rally d’un chef reste, sans chef). Son profil est conservé. Dans un tour fermé, les deux boutons sont grisés.',
 'de': 'Bearbeiten und Entfernen: Jede Zeile hat einen Stift und einen Papierkorb. Der Stift öffnet die Anmeldung mit gesperrter Spieler-ID: Schlachtstunden, Discord-Sprachchat, Lagerstufe und Tier pro Truppe. Name, Allianz und Truppen werden mit den anderen Events geteilt; eine leere Truppenstufe behält den gespeicherten Wert. Der Papierkorb fragt zuerst; steht der Spieler im Schlachtplan, wird angezeigt wo, und beim Entfernen verlässt er auch den Plan (die Rallye-Karte eines Leiters bleibt, ohne Leiter). Sein Profil bleibt erhalten. In einer geschlossenen Runde sind beide Schaltflächen ausgegraut.',
 'pl': 'Edytuj i Usuń: każdy wiersz ma ołówek i kosz. Ołówek otwiera zapis z zablokowanym ID gracza: godziny bitwy, czat głosowy Discord, poziom obozu i tier dla każdego rodzaju wojsk. Nazwa, sojusz i wojska są wspólne dla innych wydarzeń, a pusty poziom wojsk zachowuje zapisaną wartość. Kosz najpierw pyta; jeśli gracz jest w planie bitwy, pokazuje gdzie, a usunięcie zabiera go też z planu (karta rajdu lidera zostaje, bez lidera). Profil gracza zostaje. W zamkniętej rundzie oba przyciski są wyszarzone.',
 'ko': '수정과 제거: 각 행에 연필과 휴지통이 있습니다. 연필을 누르면 플레이어 ID가 잠긴 채로 신청서가 열립니다: 전투 시간, Discord 음성 채팅, 병종별 병영 레벨과 티어. 이름, 연맹, 병력은 다른 이벤트와 공유되며, 병력 레벨을 비워 두면 저장된 값이 유지됩니다. 휴지통은 먼저 확인을 묻습니다. 플레이어가 전투 계획에 있으면 위치를 알려 주고, 제거하면 계획에서도 빠집니다(리더의 집결 카드는 리더 없이 남습니다). 프로필은 유지됩니다. 마감된 라운드에서는 두 버튼이 회색으로 비활성화됩니다.',
 'zh': '编辑和移除：每行都有铅笔和垃圾桶按钮。铅笔会打开该报名，玩家 ID 锁定不可改：作战时段、Discord 语音、每种兵种的兵营等级和阶级。名字、联盟和部队与其他活动共用；部队等级留空会保留已保存的值。垃圾桶会先确认；如果玩家在作战计划中，会显示其位置，移除后也会从计划中移出（队长的集结卡片会保留，但没有队长）。玩家资料会保留。已关闭的轮次中两个按钮都会变灰。',
 'tr': 'Düzenle ve Kaldır: her satırda bir kalem ve bir çöp kutusu vardır. Kalem, oyuncu kimliği kilitli olarak kaydı açar: savaş saatleri, Discord sesli sohbet, her birlik türü için kamp seviyesi ve kademe. İsim, ittifak ve birlikler diğer etkinliklerle paylaşılır; boş bırakılan birlik seviyesi kayıtlı değeri korur. Çöp kutusu önce sorar; oyuncu savaş planındaysa nerede olduğunu söyler ve kaldırınca plandan da çıkar (bir liderin ralli kartı lidersiz kalır). Profili korunur. Kapalı bir turda iki düğme de gridir.',
 'ar': 'تعديل وإزالة: في كل صف قلم وسلة. القلم يفتح التسجيل مع قفل رقم اللاعب: ساعات المعركة، والدردشة الصوتية على Discord، ومستوى المعسكر والفئة لكل نوع قوات. الاسم والتحالف والقوات مشتركة مع الفعاليات الأخرى، وترك مستوى القوات فارغًا يُبقي القيمة المحفوظة. السلة تسأل أولًا؛ وإذا كان اللاعب في خطة المعركة تُظهر مكانه، وإزالته تُخرجه من الخطة أيضًا (تبقى بطاقة حشد القائد بلا قائد). يُحتفظ بملفه الشخصي. في الجولة المغلقة يكون الزرّان باللون الرمادي.',
}
TYR = {
 'en': 'Edit and Remove: each row has a pencil and a bin. The pencil opens the sign-up with the player ID locked: time windows, Discord voice chat, roles, power (in millions), gem spend, Discord ID, and camp level and tier per troop. Name, alliance, troops, power and Discord ID are shared with the other events, and a blank troop level keeps what is stored. The bin removes the sign-up from this round only (you are asked first); the profile is kept. In a closed round both buttons are greyed out.',
 'es': 'Editar y Quitar: cada fila tiene un lápiz y una papelera. El lápiz abre la inscripción con el ID de jugador bloqueado: franjas horarias, chat de voz de Discord, funciones, poder (en millones), gasto de gemas, ID de Discord, y nivel de campamento y rango por tropa. Nombre, alianza, tropas, poder e ID de Discord se comparten con los demás eventos, y un nivel de tropa vacío mantiene lo guardado. La papelera quita la inscripción solo de esta ronda (pregunta antes); el perfil se conserva. En una ronda cerrada ambos botones están en gris.',
 'fr': 'Modifier et Retirer : chaque ligne a un crayon et une corbeille. Le crayon ouvre l’inscription avec l’ID joueur verrouillé : créneaux, chat vocal Discord, rôles, puissance (en millions), gemmes dépensées, ID Discord, et niveau de camp et palier par troupe. Le nom, l’alliance, les troupes, la puissance et l’ID Discord sont partagés avec les autres événements, et un niveau de troupe vide garde la valeur enregistrée. La corbeille retire l’inscription de ce tour seulement (avec confirmation) ; le profil est conservé. Dans un tour fermé, les deux boutons sont grisés.',
 'de': 'Bearbeiten und Entfernen: Jede Zeile hat einen Stift und einen Papierkorb. Der Stift öffnet die Anmeldung mit gesperrter Spieler-ID: Zeitfenster, Discord-Sprachchat, Rollen, Macht (in Millionen), Edelstein-Ausgaben, Discord-ID sowie Lagerstufe und Tier pro Truppe. Name, Allianz, Truppen, Macht und Discord-ID werden mit den anderen Events geteilt; eine leere Truppenstufe behält den gespeicherten Wert. Der Papierkorb entfernt die Anmeldung nur aus dieser Runde (nach Rückfrage); das Profil bleibt. In einer geschlossenen Runde sind beide Schaltflächen ausgegraut.',
 'pl': 'Edytuj i Usuń: każdy wiersz ma ołówek i kosz. Ołówek otwiera zapis z zablokowanym ID gracza: okna czasowe, czat głosowy Discord, role, siła (w milionach), wydatek klejnotów, ID Discord oraz poziom obozu i tier dla każdego rodzaju wojsk. Nazwa, sojusz, wojska, siła i ID Discord są wspólne dla innych wydarzeń, a pusty poziom wojsk zachowuje zapisaną wartość. Kosz usuwa zapis tylko z tej rundy (po potwierdzeniu); profil zostaje. W zamkniętej rundzie oba przyciski są wyszarzone.',
 'ko': '수정과 제거: 각 행에 연필과 휴지통이 있습니다. 연필을 누르면 플레이어 ID가 잠긴 채로 신청서가 열립니다: 시간대, Discord 음성 채팅, 역할, 전투력(백만 단위), 보석 사용량, Discord ID, 병종별 병영 레벨과 티어. 이름, 연맹, 병력, 전투력, Discord ID는 다른 이벤트와 공유되며, 병력 레벨을 비워 두면 저장된 값이 유지됩니다. 휴지통은 확인 후 이 라운드에서만 신청을 제거하며 프로필은 유지됩니다. 마감된 라운드에서는 두 버튼이 회색으로 비활성화됩니다.',
 'zh': '编辑和移除：每行都有铅笔和垃圾桶按钮。铅笔会打开该报名，玩家 ID 锁定不可改：时间段、Discord 语音、职责、战力（百万）、钻石花费、Discord ID，以及每种兵种的兵营等级和阶级。名字、联盟、部队、战力和 Discord ID 与其他活动共用；部队等级留空会保留已保存的值。垃圾桶只会从本轮移除报名（会先确认），玩家资料会保留。已关闭的轮次中两个按钮都会变灰。',
 'tr': 'Düzenle ve Kaldır: her satırda bir kalem ve bir çöp kutusu vardır. Kalem, oyuncu kimliği kilitli olarak kaydı açar: zaman aralıkları, Discord sesli sohbet, roller, güç (milyon olarak), elmas harcaması, Discord kimliği ve her birlik türü için kamp seviyesi ve kademe. İsim, ittifak, birlikler, güç ve Discord kimliği diğer etkinliklerle paylaşılır; boş bırakılan birlik seviyesi kayıtlı değeri korur. Çöp kutusu kaydı yalnızca bu turdan kaldırır (önce sorar); profil korunur. Kapalı bir turda iki düğme de gridir.',
 'ar': 'تعديل وإزالة: في كل صف قلم وسلة. القلم يفتح التسجيل مع قفل رقم اللاعب: الفترات الزمنية، والدردشة الصوتية على Discord، والأدوار، والقوة (بالملايين)، وإنفاق الجواهر، ومعرّف Discord، ومستوى المعسكر والفئة لكل نوع قوات. الاسم والتحالف والقوات والقوة ومعرّف Discord مشتركة مع الفعاليات الأخرى، وترك مستوى القوات فارغًا يُبقي القيمة المحفوظة. السلة تزيل التسجيل من هذه الجولة فقط (بعد السؤال)؛ ويُحتفظ بالملف الشخصي. في الجولة المغلقة يكون الزرّان باللون الرمادي.',
}
for lang in SVS:
    p = f'{BASE}/{lang}/guide.json'
    d = json.load(open(p, encoding='utf-8'))
    d['svsAdmin']['table3'] = SVS[lang]
    d['tyrantAdmin']['deleteBody'] = TYR[lang]
    json.dump(d, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    open(p, 'a', encoding='utf-8').write('\n')
print('ok')
